version: "3.7"
services:
  web_service:
    ### dont forget to run "docker-compose build" first
    build: .
    container_name: bookstore-api-container
    # image: "bookstore-api:1.0"
    # image: "bookstore-api:latest"
    restart: always
    ports:
      - 80:80
    depends_on:
      - postgres_db
    environment:
      #SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_GENERATE_DDL: "true"
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:postgresql://postgres_db:5432/bookstore_db",
        "spring.datasource.username": "postgresUser",
        "spring.datasource.password": "postgresPass",
        "spring.datasource.driver-class": "org.postgresql.Driver",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.datasource.initialization-mode": "always",
        "bookstore.hashSecret": "${BOOKSTORE_HASH_SECRET}",
        "bookstore.adminDefaultPassword": "${BOOKSTORE_ADMIN_PASSWORD}"
      }'
  postgres_db:
    image: "postgres:11.4"
    #image: "postgres:10.16-alpine"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: bookstore_db
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgresPass
