
server:
  port: 80
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: false
    path: "/error"
spring:
  profiles:
    active: "prod"
  application:
    name: bookstore-api
  main:
    banner-mode: off
  datasource:
    auto-commit: false
  jpa:
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      enabled: true

bookstore:
  printExceptions: false

---

spring:
  config:
    activate:
      on-profile: prod
  # datasource configured via docker-compose
logging:
  level:
    org.hibernate: ERROR

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:file:./build/dev_db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8042
  error:
    include-exception: true
logging:
  level:
    org.hibernate: INFO
    org.hibernate.sql: INFO
bookstore:
  hashSecret: devSecret
  adminDefaultPassword: admin

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
bookstore:
  hashSecret: testSecret
  adminDefaultPassword: admin

---

spring:
  config:
    activate:
      on-profile: insertDummyData

---

spring:
  config:
    activate:
      on-profile: verboseErrorHandling
bookstore:
  printExceptions: true