spring:
  config:
    activate:
      on-profile: test
name: test-YAML
environment: test
enabled: false
bookstore:
  dbconfig: testUrl

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 80
name: prod-YAML
environment: production
enabled: true
bookstore:
  dbconfig: prodUrl