server:
  port: 80
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: false
spring:
  profiles:
    active: "prod"
  application:
    name: bookstore-api
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      enabled: true

---
spring:
  config:
    activate:
      on-profile: prod
    #datasource:
    #url: jdbc:foobar
    #username: ...
logging:
  level:
    org.hibernate: ERROR

---
# -Dspring.profiles.active=dev,dummyData
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  error:
    include-exception: true
logging:
  level:
#    org.hibernate: DEBUG
#    org.hibernate.sql: DEBUG

---
spring:
  config:
    activate:
      on-profile: dummyData